[package]
name = "hardware"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = {path="../utils", version="0.1.0"}
types = {path="../../types", version="0.1.0"}

[dependencies.uuid]
version = "1.15.1"
# Lets you generate random UUIDs
features = [
    "v4",
]